name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Find all Package.swift files
        run: find . -name Package.swift
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Release Binary
        run: |
          cd "Mac Hardware Info"
          swift build -c release

      - name: Run Binary (test)
        run: |
          cd "Mac Hardware Info"
          .build/release/macinfo

      - name: Upload CLI Binary
        uses: actions/upload-artifact@v4
        with:
          name: macinfo-binary
          path: Mac Hardware Info/.build/release/macinfo
