name: Build 

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Release Binary
        run: swift build -c release

      - name: Run Binary (test)
        run: .build/release/macinfo

      - name: Upload CLI Binary
        uses: actions/upload-artifact@v4
        with:
          name: macinfo-binary
          path: .build/release/macinfo
